export { default as home } from './home.vue'
export { default as exit } from './exit.vue'
export { default as face } from './face.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
export { default as up } from './up.vue'
export { default as down } from './down.vue'
